### PR TITLE
l1-RDA solver for learning sparsified solutions

### PR DESCRIPTION
**Pull request by jumutc**
Implementation for https://github.com/JuliaStats/RegERMs.jl/issues/11 based on:
Lin Xiao. Dual averaging methods for regularized stochastic learning and online optimization. J. Mach. Learn. Res., 11:2543–2596, December 2010.

### CODE REVIEW

**Comment by jumutc** [comment]
Hey, @BigCrunsh! Any comments or suggestions about this pull request?

**Comment by BigCrunsh** [comment]
@jumutc: thanks for implementing this! I was quite busy the last months and I try to get my head around this the next weeks, but I tend to just merge that PR such we can keep on going. Other opinions? @lindahua, @johnmyleswhite

**Comment by jumutc** [comment]
I'm working right now on a different library ([SALSA](https://github.com/jumutc/SALSA.jl)) which implements this approach (and others as well) in the stochastic learning framework. But from my perspective l1-RDA fits ```RegERMs.jl``` package quite well too.

**Comment by johnmyleswhite** [comment]
I think merging this seems reasonable.

**Pull request merged**
